apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jacek.borkowskiit@gmail.com
    privateKeySecretRef:
      name: cloudflare-key
    solvers:
      - dns01:
          cloudflare:
            email: jacek.borkowskiit@gmail.com 
            apiTokenSecretRef:
              name: cloudflare-api-key  # Secret with Cloudflare API token
              key: api-token
