# traefik-values.yaml
deployment:
  enabled: true

service:
  type: LoadBalancer
  loadBalancerIP:  10.72.7.123


ports:
  web:
    expose: 
      default: true

    port: 8000
    exposedPort: 80
    protocol: TCP
    # The new expose format expects an object with additional fields
    exposed: true
    entryPoints:
      - web

  websecure:
    expose: 
      default: true
    port: 8443
    exposedPort: 443
    protocol: TCP
    # The new expose format expects an object with additional fields
    exposed: true
    entryPoints:
      - websecure  

ingressRoute:
  dashboard:
    enabled: false # Disable the dashboard to avoid exposing it

providers:
  kubernetesCRD: {}
  kubernetesIngress: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: "jacek.borkowskiit@gmail.com"
      storage: "/data/acme.json"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53" # Cloudflare DNS resolver

env:
  - name: DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: dns-api-token
        key: DNS_API_TOKEN

