# ---
# apiVersion: image.toolkit.fluxcd.io/v1beta2 
# kind: ImageRepository
# metadata:
#   name: examplego-repo
#   namespace: flux-system
# spec:
#   image: jborkows/go-webserver
#   interval: 5m
# ---
# apiVersion: image.toolkit.fluxcd.io/v1beta2
# kind: ImagePolicy
# metadata:
#   name: my-latest-image-policy
#   namespace: flux-system
# spec:
#   imageRepositoryRef:
#     name: examplego-repo
#     namespace: flux-system
#   policy:
#     alphabetical:
#       order: asc
# status:
#   latestImage: jborkows/go-webserver:latest
# ---
# apiVersion: image.toolkit.fluxcd.io/v1beta2
# kind: ImageUpdateAutomation
# metadata:
#   name: my-image-update
#   namespace: flux-system
# spec:
#   update:
#     strategy: overwrite
#     path: "./deployemnt.yaml"  # Update this path as necessary
#   imagePolicyRef:
#     name: my-latest-image-policy
#     namespace: flux-system
# ---
apiVersion: v1
kind: Namespace
metadata:
  name: examplego
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webserver
  namespace: examplego
  labels:
    app: go-webserver
    autodeploy: "true"
spec:
  replicas: 3  # Number of desired pods
  selector:
    matchLabels:
      app: go-webserver
  template:
    metadata:
      annotations:
        diun.enable: "true"
      labels:
        app: go-webserver
    spec:
      containers:
      - name: go-webserver
        image: jborkows/go-webserver:latest  # Replace with your image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-webserver
  namespace: examplego
spec:
  selector:
    app: go-webserver
  ports:
    - protocol: TCP
      port: 8080  # External port
      targetPort: 8080  # Port that the container listens on
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: examplego
  annotations:
    cert-manager.io/cluster-issuer: "cloudflare"  # Reference the ClusterIssuer
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: examplego.borkowskij.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-webserver
            port:
              number: 8080
  tls:
  - hosts:
    - examplego.borkowskij.com
    secretName: examplego-borkowskij-com-tls


